import type { ComponentType } from 'react';
import type { IconProps } from './types';
import {
  AlarmIcon,
  ArrowIcon,
  BackupIcon,
  CalendarIcon,
  Category1Icon,
  CategoryIcon,
  CheckIcon,
  CloseIcon,
  DistanceIcon,
  FavoriteIcon,
  FireButtonIcon,
  FireIcon,
  FlagIcon,
  GoogleIcon,
  HPIcon,
  HandIcon,
  HeartIcon,
  KakaoIcon,
  MoreIcon,
  NotificationsIcon,
  PaginationIcon,
  PeriodIcon,
  Person1Icon,
  PersonIcon,
  ProjectIcon,
  RatingIcon,
  ReplayIcon,
  RisingIcon,
  SearchIcon,
  StateIcon,
  StudyIcon,
  TimeIcon,
  TypeIcon,
  VisibilityIcon,
} from './index';

export interface IconRegistryItem {
  component: ComponentType<IconProps>;
  variants?: readonly string[];
  fixedColor?: boolean;
}

export const iconsRegistry: Record<string, IconRegistryItem> = {
  AlarmIcon: { component: AlarmIcon },
  ArrowIcon: { component: ArrowIcon, variants: ['left', 'right'] },
  BackupIcon: { component: BackupIcon },
  CalendarIcon: { component: CalendarIcon },
  Category1Icon: { component: Category1Icon },
  CategoryIcon: { component: CategoryIcon },
  CheckIcon: { component: CheckIcon },
  CloseIcon: { component: CloseIcon },
  DistanceIcon: { component: DistanceIcon },
  FavoriteIcon: { component: FavoriteIcon, variants: ['outline', 'filled'] },
  FireButtonIcon: { component: FireButtonIcon, variants: ['active', 'disabled'], fixedColor: true },
  FireIcon: { component: FireIcon },
  FlagIcon: { component: FlagIcon },
  GoogleIcon: { component: GoogleIcon, fixedColor: true },
  HPIcon: { component: HPIcon },
  HandIcon: { component: HandIcon },
  HeartIcon: { component: HeartIcon, variants: ['outline', 'filled'] },
  KakaoIcon: { component: KakaoIcon, fixedColor: true },
  MoreIcon: { component: MoreIcon },
  NotificationsIcon: { component: NotificationsIcon },
  PaginationIcon: { component: PaginationIcon, variants: ['prev', 'next'] },
  PeriodIcon: { component: PeriodIcon },
  Person1Icon: { component: Person1Icon },
  PersonIcon: { component: PersonIcon },
  ProjectIcon: { component: ProjectIcon },
  RatingIcon: { component: RatingIcon, variants: ['gold', 'silver', 'bronze'], fixedColor: true },
  ReplayIcon: { component: ReplayIcon },
  RisingIcon: { component: RisingIcon },
  SearchIcon: { component: SearchIcon },
  StateIcon: { component: StateIcon, variants: ['active', 'warning'] },
  StudyIcon: { component: StudyIcon },
  TimeIcon: { component: TimeIcon },
  TypeIcon: { component: TypeIcon },
  VisibilityIcon: { component: VisibilityIcon, variants: ['off', 'on'] },
};
