import type { ComponentType } from 'react';
import type { IconProps } from './types';
import {
  AlarmIcon,
  ArrowIcon,
  BackupIcon,
  CalendarIcon,
  CategoryIcon,
  CheckIcon,
  CloseIcon,
  CollaborationMannersIcon,
  CompletedIcon,
  DistanceIcon,
  EmailIcon,
  FireButtonIcon,
  FlagIcon,
  GoalManagementIcon,
  IllustrationIcon,
  GoogleIcon,
  HPIcon,
  HandIcon,
  HeartIcon,
  InfoIcon,
  KakaoIcon,
  MoreIcon,
  NotificationsIcon,
  PaginationIcon,
  PeopleIcon,
  PeriodIcon,
  PersonIcon,
  ProjectIcon,
  ProgressIcon,
  RatingIcon,
  RecruitingIcon,
  ReplayIcon,
  ReviewIcon,
  RisingIcon,
  SearchIcon,
  LandingSearchIcon,
  StateIcon,
  StudyIcon,
  TeamBuildingIcon,
  LandingLocationIcon,
  LandingPaperIcon,
  LandingActivityIcon,
  LandingAddIcon,
  LandingCheckIcon,
  LandingFlagIcon,
  LandingHeartIcon,
  TimeIcon,
  TypeIcon,
  VisibilityIcon,
  WaitingIcon,
  AchievementTrackingIcon,
} from './index';

export interface IconRegistryItem {
  component: ComponentType<IconProps>;
  variants?: readonly string[];
  fixedColor?: boolean;
}

export const iconsRegistry: Record<string, IconRegistryItem> = {
  AlarmIcon: { component: AlarmIcon },
  ArrowIcon: { component: ArrowIcon },
  BackupIcon: { component: BackupIcon },
  CalendarIcon: { component: CalendarIcon },
  CategoryIcon: { component: CategoryIcon },
  CheckIcon: { component: CheckIcon },
  CloseIcon: { component: CloseIcon },
  CollaborationMannersIcon: { component: CollaborationMannersIcon, fixedColor: true },
  CompletedIcon: { component: CompletedIcon },
  DistanceIcon: { component: DistanceIcon },
  EmailIcon: { component: EmailIcon },
  FireButtonIcon: { component: FireButtonIcon, variants: ['active', 'disabled'], fixedColor: true },
  IllustrationIcon: {
    component: IllustrationIcon,
    variants: ['fire', 'smoke', 'firestart', 'sun'],
    fixedColor: true,
  },
  FlagIcon: { component: FlagIcon },
  GoalManagementIcon: { component: GoalManagementIcon, fixedColor: true },
  GoogleIcon: { component: GoogleIcon, fixedColor: true },
  HPIcon: { component: HPIcon },
  HandIcon: { component: HandIcon },
  HeartIcon: { component: HeartIcon, variants: ['outline', 'filled'] },
  InfoIcon: { component: InfoIcon },
  KakaoIcon: { component: KakaoIcon, fixedColor: true },
  MoreIcon: { component: MoreIcon },
  NotificationsIcon: { component: NotificationsIcon },
  PaginationIcon: { component: PaginationIcon, variants: ['prev', 'next'] },
  PeopleIcon: { component: PeopleIcon },
  PeriodIcon: { component: PeriodIcon },
  PersonIcon: { component: PersonIcon },
  ProjectIcon: { component: ProjectIcon },
  ProgressIcon: { component: ProgressIcon },
  RatingIcon: { component: RatingIcon, variants: ['gold', 'silver', 'bronze'], fixedColor: true },
  RecruitingIcon: { component: RecruitingIcon },
  ReplayIcon: { component: ReplayIcon },
  ReviewIcon: { component: ReviewIcon },
  RisingIcon: { component: RisingIcon },
  SearchIcon: { component: SearchIcon },
  LandingSearchIcon: { component: LandingSearchIcon, fixedColor: true },
  StateIcon: { component: StateIcon, variants: ['active', 'warning'] },
  StudyIcon: { component: StudyIcon },
  TeamBuildingIcon: { component: TeamBuildingIcon, fixedColor: true },
  LandingLocationIcon: { component: LandingLocationIcon, fixedColor: true },
  LandingPaperIcon: { component: LandingPaperIcon, fixedColor: true },
  LandingActivityIcon: { component: LandingActivityIcon, fixedColor: true },
  LandingAddIcon: { component: LandingAddIcon, fixedColor: true },
  LandingCheckIcon: { component: LandingCheckIcon, fixedColor: true },
  LandingFlagIcon: { component: LandingFlagIcon, fixedColor: true },
  LandingHeartIcon: { component: LandingHeartIcon, fixedColor: true },
  TimeIcon: { component: TimeIcon },
  TypeIcon: { component: TypeIcon },
  VisibilityIcon: { component: VisibilityIcon, variants: ['off', 'on'] },
  WaitingIcon: { component: WaitingIcon },
  AchievementTrackingIcon: { component: AchievementTrackingIcon, fixedColor: true },
};
